allowBuilds:
  cn-font-split: true
  esbuild: true
  koffi: true
  protobufjs: true
  sharp: true

patchedDependencies:
  cn-font-split@7.4.3: patches/cn-font-split@7.4.3.patch

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
