name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: voidzero-dev/setup-vp@4f5aa3e38c781f1b01e78fb9255527cee8a6efa6
        with:
          node-version: '24'
          cache: true
      - run: vp build

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      # coscmd does not support Python 3.12+
      # https://github.com/tencentyun/coscmd/issues/311
      - run: |
          uvx --python 3.11 coscmd config \
            -a ${{ secrets.TENCENT_CLOUD_SECRET_ID }} \
            -s ${{ secrets.TENCENT_CLOUD_SECRET_KEY }} \
            -b ${{ secrets.TENCENT_CLOUD_COS_BUCKET }} \
            -r ${{ secrets.TENCENT_CLOUD_COS_REGION }}
      - run: uvx --python 3.11 coscmd upload -r dist/client/ /
